queue_rules:
  - name: default
    conditions:
      - or:
        - and:
          - -files~=\.hs$
          - -files~=\.disco$
          - -files~=\.cabal$
          - -files=stack.yaml
        - and:
          - check-success=Haskell-CI - Linux - ghc-9.8.2
          - check-success=Haskell-CI - Linux - ghc-9.6.5
          - check-success=Haskell-CI - Linux - ghc-9.4.8

pull_request_rules:
- actions:
    queue:
      name: default
      method: squash
      commit_message_template: |
        {{ title }} (#{{ number }})

        {{ body }}

  name: Automatically merge pull requests
  conditions:
  - or:
    - and:
      - -files~=\.hs$
      - -files~=\.disco$
      - -files~=\.cabal$
      - -files=stack.yaml
    - and:
      - check-success=Haskell-CI - Linux - ghc-9.8.2
      - check-success=Haskell-CI - Linux - ghc-9.6.5
      - check-success=Haskell-CI - Linux - ghc-9.4.8
  - label=merge me
  - ! '#approved-reviews-by>=1'
  - ! '#changes-requested-reviews-by=0'
- actions:
    delete_head_branch: {}
  name: Delete head branch after merge
  conditions:
  - merged
